version: 2

seeds:
  - name: Sales_Product_Combined
    description: "Seed file containing sales and product data"
    columns:
      - name: "Order ID"
        description: "Unique identifier for each order"
      - name: Product
        description: "Name of the product"
      - name: "Quantity Ordered"
        description: "Quantity of the product ordered"
      - name: Price
        description: "Price of the product"
      - name: "Order Date"
        description: "Date when the order was placed"
      - name: "Purchase Address"
        description: "Address where the product was delivered"
